import { ReactElement } from "react";
import type { IconType } from "react-icons/lib";

export * from "./mail";
export * from "./referrals";
export type MenuConfig = {
  icon: IconType;
  name: string;
  id: string;
  link: string;
  submenu?: MenuConfig[];
  header?: () => ReactElement;
  onClick?: (e: React.MouseEvent<HTMLAnchorElement, MouseEvent>) => void;
  skipRender?: boolean;
};

export enum QueryKeys {
  "JUPITER_QUOTE" = "JUPITER_QUOTE",
  "JUPITER_TOKENS" = "JUPITER_TOKENS",
  "ENCRYPTION_KEY" = "ENCRYPTION_KEY",
  "MAIL_BODY" = "MAIL_BODY",
  "MAILBOX" = "MAILBOX",
  "LABEL_INDEX_UPDATE" = "LABEL_INDEX_UPDATE",
  "MAILBOX_STATUS" = "MAILBOX_STATUS",
  "CREATE_MAILBOX" = "CREATE_MAILBOX",
  "CREATE_CREDENTIALS" = "CREATE_CREDENTIALS",
  "SOL_BALANCE" = "SOL_BALANCE",
  "JUPITER_SOL_BALANCE" = "JUPITER_SOL_BALANCE",
  "USER_PROFILE" = "USER_PROFILE",
  "CREATE_USER_PROFILE" = "CREATE_USER_PROFILE",
  "REWARDS_LIST" = "REWARDS_LIST",
  "UPDATE_REFERAL_CODE" = "UPDATE_REFERAL_CODE",
  "USERNAME_STATUS" = "USERNAME_STATUS",
  "GET_USERNAMES" = "GET_USERNAMES",
  "EMAIL_RESOLVER" = "EMAIL_RESOLVER",
  "MILESTONES" = "MILESTONES",
  "QUICKNODE" = "QUICKNODE",
  "TRANSFER" = "TRANSFER",
  "CLAIM_USERNAME" = "CLAIM_USERNAME",
  "QUICK_NODE_QUERY" = "QUICK_NODE_QUERY",
  "PAYMENT_STATUS" = "PAYMENT_STATUS",
  "TOKENS" = "TOKENS",
  "UNLINNK_USERNAME" = "UNLINNK_USERNAME",
  "PAYMENT_TRANSFER" = "PAYMENT_TRANSFER",
  "SOL_PRICE" = "SOL_PRICE",
  "GET_USERNAMES_BY_ID" = "GET_USERNAMES_BY_ID",
  "TRANSACTION_INFO" = "TRANSACTION_INFOF",
  "JUPITER_PRICE" = "JUPITER_PRICE",
  "HELIUS_GNERIC" = "HELIUS_GNERIC",
  "WEB_2_MAIL" = "WEB_2_MAIL",
  "TOKEN_REFRESHER" = "TOKEN_REFRESHER",
  "USERNAME_VERIFY" = "USERNAME_VERIFY",

  "MUTATION_GET_SIGNER_MESSAGE" = "MUTATION_GET_SIGNER_MESSAGE",
  "MUTATION_PINATA_TOKEN" = "MUTATION_PINATA_TOKEN",
  "MUTATION_UPLOAD_TO_PINATA" = "MUTATION_UPLOAD_TO_PINATA",
  "MUTATION_VALIDATE_REF_CODE" = "MUTATION_VALIDATE_REF_CODE",
  "MUTATION_FCM" = -"MUTATION_FCM",
  "MUTATION_EMAILER" = "MUTATION_EMAILER",
  "MUATATION_SEND_EMAIL" = "MUATATION_SEND_EMAIL",
  "MUTATION_V2_MAIL_REGISTER" = "MUTATION_V2_MAIL_REGISTER",
  "MUTATION_MAIL_TOKEN_CLAIM" = "MUTATION_MAIL_TOKEN_CLAIM",
  "MUTATION_REF_CODE_VALIDATOR" = "MUTATION_REF_CODE_VALIDATOR",
  "MUTATION_JUPITER_SWAP" = "MUTATION_JUPITER_SWAP",
  "MUTATION_CREATE_COMPRESSED_ACCOUNT" = "MUTATION_CREATE_COMPRESSED_ACCOUNT",
}

export type StatusType = {
  isChecking: boolean;
  isDone: boolean;
};

export type Token = {
  id: string;
  name: string;
  symbol: string;
  logo: string;
  address: string;
  decimals: number;
};

export type SolanaPayPayload = {
  recipient: string;
  amount: string;
  message: string;
  tokenaddress: string;
};
